# Generated by Django 3.0.5 on 2022-12-26 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20221225_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='chronic_illness',
            field=models.ManyToManyField(blank=True, null=True, to='users.ChronicIllness'),
        ),
    ]
