# Generated by Django 3.0.5 on 2022-12-29 14:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20221226_1817'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ratting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name=[])),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name=[])),
                ('stars', models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('comment', models.CharField(blank=True, max_length=1000, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.PatientProfile')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.SpecialistProfile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
