# Generated by Django 3.0.5 on 2022-12-31 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20221230_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='otp',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='active'),
        ),
    ]
