# Generated by Django 3.0.5 on 2023-01-03 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20221231_0322'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialistprofile',
            name='allow_Messages',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='specialistprofile',
            name='allow_booking',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='fcm_token',
            field=models.CharField(blank=True, max_length=100000, null=True),
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.PatientProfile')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.SpecialistProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name=[])),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name=[])),
                ('text', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
