# Generated by Django 3.0.5 on 2023-01-04 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20230103_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='chronicillness',
            name='special_type',
            field=models.CharField(choices=[('BABY_CARE', 'Baby Care'), ('ELDERLY_CARE', 'Elderly Care'), ('DOCTOR', 'Doctor'), ('NURSE', 'Nurse'), ('PHYSICIAN', 'Physician')], max_length=50, null=True, verbose_name='type'),
        ),
    ]
