# Generated by Django 3.0.5 on 2023-01-04 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_chronicillness_special_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialistprofile',
            name='medical_type',
            field=models.CharField(choices=[('ALLERGY_AND_IMMUNOLOGY', 'Allergy And Immunology'), ('ANESTHESIOLOGY', 'Anesthesiology'), ('DERMATOLOGY', 'Dermatology'), ('DIAGNOSTIC_RADIOLOGY', 'Diagnostic Radiology'), ('EMERGENCY_MEDICINE', 'Emergency Medicine'), ('FAMILY_MEDICINE', 'Family Medicine'), ('INTERNAL_MEDICINE', 'Internal Medicine'), ('MEDICAL_GENETICS', 'Medical Genetics'), ('NEUROLOGY', 'Neurology'), ('NUCLEAR_MEDICINE', 'Nuclear Medicine'), ('OBSTETRICS_AND_GYNECOLOGY', 'Obstetrics And Gynecology'), ('OPHTHALMOLOGY', 'Ophthalmology'), ('PATHOLOGY', 'Pathology'), ('PEDIATRICS', 'Pediatrics'), ('PHYSICAL_MEDICINE_AND_REHABILITATION', 'Physical Medicine And Rehabilitation'), ('PREVENTIVE_MEDICINE', 'Preventive Medicine'), ('PSYCHIATRY', 'Psychiatry'), ('RADIATION_ONCOLOGY', 'Radiation Oncology'), ('SURGERY', 'Surgery'), ('UROLOGY', 'Urology'), ('OTHER', 'Other')], max_length=1000, null=True, verbose_name='medical type'),
        ),
        migrations.AlterField(
            model_name='chronicillness',
            name='special_type',
            field=models.CharField(choices=[('ALLERGY_AND_IMMUNOLOGY', 'Allergy And Immunology'), ('ANESTHESIOLOGY', 'Anesthesiology'), ('DERMATOLOGY', 'Dermatology'), ('DIAGNOSTIC_RADIOLOGY', 'Diagnostic Radiology'), ('EMERGENCY_MEDICINE', 'Emergency Medicine'), ('FAMILY_MEDICINE', 'Family Medicine'), ('INTERNAL_MEDICINE', 'Internal Medicine'), ('MEDICAL_GENETICS', 'Medical Genetics'), ('NEUROLOGY', 'Neurology'), ('NUCLEAR_MEDICINE', 'Nuclear Medicine'), ('OBSTETRICS_AND_GYNECOLOGY', 'Obstetrics And Gynecology'), ('OPHTHALMOLOGY', 'Ophthalmology'), ('PATHOLOGY', 'Pathology'), ('PEDIATRICS', 'Pediatrics'), ('PHYSICAL_MEDICINE_AND_REHABILITATION', 'Physical Medicine And Rehabilitation'), ('PREVENTIVE_MEDICINE', 'Preventive Medicine'), ('PSYCHIATRY', 'Psychiatry'), ('RADIATION_ONCOLOGY', 'Radiation Oncology'), ('SURGERY', 'Surgery'), ('UROLOGY', 'Urology'), ('OTHER', 'Other')], max_length=50, null=True, verbose_name='type'),
        ),
    ]
