# Generated by Django 3.0.5 on 2023-01-10 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20230106_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(default='upcoming', max_length=50, null=True, verbose_name='appointment status'),
        ),
        migrations.AlterField(
            model_name='chronicillness',
            name='special_type',
            field=models.CharField(choices=[('ALLERGY AND IMMUNOLOGY', 'Allergy And Immunology'), ('ANESTHESIOLOGY', 'Anesthesiology'), ('DERMATOLOGY', 'Dermatology'), ('DIAGNOSTIC RADIOLOGY', 'Diagnostic Radiology'), ('EMERGENCY MEDICINE', 'Emergency Medicine'), ('FAMILY MEDICINE', 'Family Medicine'), ('INTERNAL MEDICINE', 'Internal Medicine'), ('MEDICAL GENETICS', 'Medical Genetics'), ('NEUROLOGY', 'Neurology'), ('NUCLEAR MEDICINE', 'Nuclear Medicine'), ('OBSTETRICS AND GYNECOLOGY', 'Obstetrics And Gynecology'), ('OPHTHALMOLOGY', 'Ophthalmology'), ('PATHOLOGY', 'Pathology'), ('PEDIATRICS', 'Pediatrics'), ('PHYSICAL MEDICINE AND REHABILITATION', 'Physical Medicine And Rehabilitation'), ('PREVENTIVE MEDICINE', 'Preventive Medicine'), ('PSYCHIATRY', 'Psychiatry'), ('RADIATION ONCOLOGY', 'Radiation Oncology'), ('SURGERY', 'Surgery'), ('UROLOGY', 'Urology'), ('OTHER', 'Other')], max_length=50, null=True, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='specialistprofile',
            name='medical_type',
            field=models.CharField(choices=[('ALLERGY AND IMMUNOLOGY', 'Allergy And Immunology'), ('ANESTHESIOLOGY', 'Anesthesiology'), ('DERMATOLOGY', 'Dermatology'), ('DIAGNOSTIC RADIOLOGY', 'Diagnostic Radiology'), ('EMERGENCY MEDICINE', 'Emergency Medicine'), ('FAMILY MEDICINE', 'Family Medicine'), ('INTERNAL MEDICINE', 'Internal Medicine'), ('MEDICAL GENETICS', 'Medical Genetics'), ('NEUROLOGY', 'Neurology'), ('NUCLEAR MEDICINE', 'Nuclear Medicine'), ('OBSTETRICS AND GYNECOLOGY', 'Obstetrics And Gynecology'), ('OPHTHALMOLOGY', 'Ophthalmology'), ('PATHOLOGY', 'Pathology'), ('PEDIATRICS', 'Pediatrics'), ('PHYSICAL MEDICINE AND REHABILITATION', 'Physical Medicine And Rehabilitation'), ('PREVENTIVE MEDICINE', 'Preventive Medicine'), ('PSYCHIATRY', 'Psychiatry'), ('RADIATION ONCOLOGY', 'Radiation Oncology'), ('SURGERY', 'Surgery'), ('UROLOGY', 'Urology'), ('OTHER', 'Other')], max_length=1000, null=True, verbose_name='medical type'),
        ),
    ]
