# Generated by Django 3.0.5 on 2023-01-10 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20230110_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='chat_bot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='caht_bot', to='users.ChronicIllness'),
        ),
    ]
