# Generated by Django 3.0.5 on 2023-01-11 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_notification_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='date',
        ),
    ]
