# Generated by Django 3.0.5 on 2023-01-12 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_remove_notification_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='symptoms',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Symptoms'),
        ),
        migrations.AddField(
            model_name='symptoms',
            name='special_type',
            field=models.CharField(choices=[('ALLERGY AND IMMUNOLOGY', 'Allergy And Immunology'), ('ANESTHESIOLOGY', 'Anesthesiology'), ('DERMATOLOGY', 'Dermatology'), ('DIAGNOSTIC RADIOLOGY', 'Diagnostic Radiology'), ('EMERGENCY MEDICINE', 'Emergency Medicine'), ('FAMILY MEDICINE', 'Family Medicine'), ('INTERNAL MEDICINE', 'Internal Medicine'), ('MEDICAL GENETICS', 'Medical Genetics'), ('NEUROLOGY', 'Neurology'), ('NUCLEAR MEDICINE', 'Nuclear Medicine'), ('OBSTETRICS AND GYNECOLOGY', 'Obstetrics And Gynecology'), ('OPHTHALMOLOGY', 'Ophthalmology'), ('PATHOLOGY', 'Pathology'), ('PEDIATRICS', 'Pediatrics'), ('PHYSICAL MEDICINE AND REHABILITATION', 'Physical Medicine And Rehabilitation'), ('PREVENTIVE MEDICINE', 'Preventive Medicine'), ('PSYCHIATRY', 'Psychiatry'), ('RADIATION ONCOLOGY', 'Radiation Oncology'), ('SURGERY', 'Surgery'), ('UROLOGY', 'Urology'), ('OTHER', 'Other')], max_length=50, null=True, verbose_name='type'),
        ),
    ]
