# Generated by Django 3.0.5 on 2023-01-13 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20230113_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar1',
            field=models.CharField(blank=True, max_length=1000000000, null=True),
        ),
    ]
