# Generated by Django 3.0.5 on 2023-01-15 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_specialistprofile_fav'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialistprofile',
            name='Fav',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
