from django.db import models


class Gender(models.TextChoices):
    MALE = "MALE"
    FEMALE = "FEMALE"
    OTHER = "OTHER"


class BloodType(models.TextChoices):
    A_RHD_POSITIVE = "A+"
    A_RHD_NEGATIVE = "A-"

    B_RHD_POSITIVE = "B+"
    B_RHD_NEGATIVE = "B-"

    O_RHD_POSITIVE = "O+"
    O_RHD_NEGATIVE = "O-"

    AB_RHD_POSITIVE = "AB+"
    AB_RHD_NEGATIVE = "AB-"


class UserType(models.TextChoices):
    ADMIN = "ADMIN"
    PATIENT = "PATIENT"
    SPECIALIST = "SPECIALIST"


class MedicalType(models.TextChoices):
    ALLERGY_AND_IMMUNOLOGY = 'ALLERGY AND IMMUNOLOGY'
    ANESTHESIOLOGY = 'ANESTHESIOLOGY'
    DERMATOLOGY = 'DERMATOLOGY'
    DIAGNOSTIC_RADIOLOGY = 'DIAGNOSTIC RADIOLOGY'
    EMERGENCY_MEDICINE = 'EMERGENCY MEDICINE'
    FAMILY_MEDICINE = 'FAMILY MEDICINE'
    INTERNAL_MEDICINE = 'INTERNAL MEDICINE'
    MEDICAL_GENETICS = 'MEDICAL GENETICS'
    NEUROLOGY = 'NEUROLOGY'
    NUCLEAR_MEDICINE = 'NUCLEAR MEDICINE'
    OBSTETRICS_AND_GYNECOLOGY = 'OBSTETRICS AND GYNECOLOGY'
    OPHTHALMOLOGY = 'OPHTHALMOLOGY'
    PATHOLOGY = 'PATHOLOGY'
    PEDIATRICS = 'PEDIATRICS'
    PHYSICAL_MEDICINE_AND_REHABILITATION = 'PHYSICAL MEDICINE AND REHABILITATION'
    PREVENTIVE_MEDICINE = 'PREVENTIVE MEDICINE'
    PSYCHIATRY = 'PSYCHIATRY'
    RADIATION_ONCOLOGY = 'RADIATION ONCOLOGY'
    SURGERY = 'SURGERY'
    UROLOGY = 'UROLOGY'
    Oncology_Nurse = 'Oncology Nurse'
    general = 'General Nurse'
    chest_illness = 'chest illness'
    OTHER = 'OTHER'

    test =' '


class InternalCustomAdminActions(models.TextChoices):
    ADMIN_CREATE_NEW_USER = "ADMIN_CREATE_NEW_USER"
    ADMIN_CHANGE_USER_PASSWORD = "ADMIN_CHANGE_USER_PASSWORD"
    ADMIN_CHANGE_USER_INFO = "ADMIN_CHANGE_USER_INFO"
    REGISTERED_USER = "REGISTERED_USER"


class SpecialistType(models.TextChoices):
    BABY_CARE = "BABY_CARE"
    ELDERLY_CARE = "ELDERLY_CARE"
    DOCTOR = "DOCTOR"
    NURSE = "NURSE"
    PHYSICIAN = "PHYSICIAN"


class CollegesDegrees(models.TextChoices):
    PROFESSIONAL_CERTIFICATE = "PROFESSIONAL_CERTIFICATE"
    UNDERGRADUATE_DEGREE = "UNDERGRADUATE_DEGREE"
    TRANSFER_DEGREE = "TRANSFER_DEGREE"
    ASSOCIATE_DEGREE = "ASSOCIATE_DEGREE"
    BACHELOR_DEGREE = "BACHELOR_DEGREE"
    MASTER_DEGREE = "MASTER_DEGREE"
    DOCTORAL_DEGREE = "DOCTORAL_DEGREE"
    PROFESSIONAL_DEGREE = "PROFESSIONAL_DEGREE"
    SPECIALIST_DEGREE = "SPECIALIST_DEGREE"
